server:
    port: 8085

eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    instance:
        hostname: ${HOSTNAME:localhost}
        prefer-ip-address: true


## Enable service discovery (with Eureka)
## lower-case-service-id is mandatory, otherwise is retrieved in upper case from Eureka
spring:
    application:
        name: gateway

    cloud:
        gateway:
          routes:
            - id: mscb
              uri: lb://MS-CATALOGUE-BOOKS
              predicates:
                - Path=/mscb/**
              filters:
                StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: routes, info